In [ ]:
import pandas as p
import psycopg2
pgconn = psycopg2.connect(dbname='LIvraison',user='postgres',password='oussama938',port=5432,
                          options='-c search_path=Livraison,public')
Livraison_df = p.read_sql_query('select * from "Livraison".livraison',con=pgconn)
fournisseur_df = p.read_sql_query('select * from "Livraison".fournisseur',con=pgconn)
chemin_df=p.read_sql_query('select * from "Livraison".chemin',con=pgconn)
temps_df=p.read_sql_query('select * from "Livraison".temps',con=pgconn)
print(Livraison_df.head())
print(fournisseur_df.head())
print(chemin_df.head())
print(temps_df.head())

In [5]:
import atoti as tt
session = tt.create_session(config={"port": 9089})
session.link()

Open the notebook in JupyterLab with the atoti extension enabled to see this link.

In [6]:
Livraison_table = session.read_pandas(Livraison_df, keys=['id_fournisseur','id_temps','id_chemin'], table_name="CubeLivraison")
fournisseur_table = session.read_pandas(fournisseur_df, keys=['id_fournisseur'], table_name="fournisseur")
Livraison_table.join(fournisseur_table, mapping={"id_fournisseur": "id_fournisseur"})

In [7]:
fournisseur_table.head()

,nomfournisseur,addressfournisseur
id_fournisseur,,
Griffith Paving and Sealcoatin:talend@apres91,Griffith Paving and Sealcoatin,talend@apres91
Bill's Dive Shop:511 Maple Ave. Apt. 1B,Bill's Dive Shop,511 Maple Ave. Apt. 1B
Childress Child Day Care:662 Lyons Circle,Childress Child Day Care,662 Lyons Circle
Facelift Kitchen and Bath:unknown,Facelift Kitchen and Bath,unknown
Terrinni & Son Auto and Truck:770 Exmoor Rd.,Terrinni & Son Auto and Truck,770 Exmoor Rd.

In [8]:
Livraison_table.head()

,,,qte,prix_commande
id_temps,id_fournisseur,id_chemin,,
03/11/2006 09:20 : 26:40.0,Griffith Paving and Sealcoatin:talend@apres91,"PN"":Iles Pitcairn->PN"":Iles Pitcairn",67852.0,61521.484
19/11/2004 15:48 : 40:00.0,Bill's Dive Shop:511 Maple Ave. Apt. 1B,"MH"":Iles Marshall->DE"":Allemagne",88792.0,15434.100
16/02/2005 08:27 : 00:00.0,Childress Child Day Care:662 Lyons Circle,"AF"":Afghanistan->BT"":Bhoutan",35340.0,17856.880
22/08/2002 09:55 : 00:00.0,Facelift Kitchen and Bath:unknown,":->AW"":Aruba",6097.0,55560.240
28/06/2001 09:15 : 26:40.0,Terrinni & Son Auto and Truck:770 Exmoor Rd.,":->AQ"":Antarctique",5146.0,39098.113

In [9]:
chemin_table = session.read_pandas(chemin_df, keys=['id_chemin'], table_name="chemin")
Livraison_table.join(chemin_table, mapping={"id_chemin": "id_chemin"})

In [10]:
chemin_table.head()

,id_pays,nom_pays,id_payslivraison,nom_payslivraison
id_chemin,,,,
"PN"":Iles Pitcairn->PN"":Iles Pitcairn","PN""",Iles Pitcairn,"PN""",Iles Pitcairn
"MH"":Iles Marshall->DE"":Allemagne","MH""",Iles Marshall,"DE""",Allemagne
"AF"":Afghanistan->BT"":Bhoutan","AF""",Afghanistan,"BT""",Bhoutan
":->AW"":Aruba",,,"AW""",Aruba
":->AQ"":Antarctique",,,"AQ""",Antarctique

In [11]:
temps_table = session.read_pandas(temps_df, keys=['id_temps'], table_name="temps")
Livraison_table.join(temps_table, mapping={"id_temps": "id_temps"})

In [12]:
temps_table.head()

                                 datelivraison tempslivraison
id_temps
03/11/2006 09:20  :  26:40.0  03/11/2006 09:20        26:40.0
19/11/2004 15:48  :  40:00.0  19/11/2004 15:48        40:00.0
16/02/2005 08:27  :  00:00.0  16/02/2005 08:27        00:00.0
22/08/2002 09:55  :  00:00.0  22/08/2002 09:55        00:00.0
28/06/2001 09:15  :  26:40.0  28/06/2001 09:15        26:40.0

In [14]:
cube = session.create_cube(Livraison_table)

AtotiJavaException: Agent illegal state transition detected: trying to change from INIT to STOPPED but the authorized previous states are [STARTED, PAUSED].

In [35]:
session.visualize()

Open the notebook in JupyterLab with the atoti extension enabled to build this widget.

NameError: name 'cube' is not defined